language: python

cache: pip

script: skip

branches:
  only:
    - "master"

skip_commits:
  files:
    - setup.py

notifications:
  email:
    on_failure: never
    on_pull_requests: never

deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  on:
    branch:
      - master

  user: ${PYPI_USERNAME}
  password : ${PYPI_PASSWORD}